collections:
  - common
  - purescript

excludes:
  - .cspell.json
  - README.md
  - bower.json
  - package.json
  - spago.dhall

render_context:
  project:
    name: purescript-array-search
    description: Array search utilities.
    version: 0.2.0
    verbose_name: PureScript Array Search
    repository: https://github.com/JoelLefkowitz/purescript-array-search
    codacy_id: a234d28178cf4a1b8bca450fdc432f77

  author:
    author: joellefkowitz
    author_email: joellefkowitz@hotmail.com
    verbose_author: Joel Lefkowitz

clear_top_level: true
logical_grouping: true

loader_paths:
  - docs
