severity: low
exclude:
  - message: Codacy project public id
    pattern: a234d28178cf4a1b8bca450fdc432f77

  - message: Giphy links
    pattern: https://media.giphy.com/media/

  - message: Build output
    paths:
      - output/cache-db.json

  - message: Docs output
    paths:
      - generated-docs

  - message: Old test output
    paths:
      - .nyc_output

  - message: Dependencies
    paths:
      - bower_components
      - node_modules
      - package-lock.json
      - packages.dhall
      - spago.dhall
      - venv
      - yarn-error.log
      - yarn.lock
