name: Review

on: [push, pull_request]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/actions/install

      - name: Run linters
        run: nps lint

      - name: Check the build completes
        run: nps build

      - name: Run tests
        run: nps test

      - name: Verify pulp and bower complete
        run: |
          npx bower install --production
          npx pulp build
